<div id="sidebar">
	<div id="search">
		<form method="get" action="http://seekingmichigan.org">
		<h2>About Teacher Resources</h2>
		<p>These materials are resources generated by the Michigan Historical Center to help teachers engage with Michigan's history.</p>
		<input type="text" name="s" id="search-text" value="" />
		<input type="hidden" value="resources" name="category_name" />
		<input type="image" src="http://seekingmichigan.org/images/search-button.png" id="search-button" name="search-button" value=" " />
		</form>
	</div>
	<div id="sidebar-options">
		<h2>Find Lessons by Subject:</h2>
		<ul>
			<li><a href="http://seekingmichigan.org/coming-soon">Statehood</a></li>
			<li><a href="http://seekingmichigan.org/coming-soon">Pioneer Life</a></li>
			<li><a href="http://seekingmichigan.org/coming-soon">Civil War</a></li>
		</ul>
	</div>  	
	<div id="sidebar-info">
		<ul>
			<li><a href="http://seekingmichigan.org/visit-us">Visit Us</a></li>
			<li><a href="http://www.michigan.gov/dnr/0,4570,7-153-54463_18595_18596-262027--,00.html">Admissions</a></li>
		</ul>
	</div>
	
	<div id="sidebar-btn">
		<ul>
			<li>
				<a href="http://www.loc.gov/teachers/usingprimarysources/index.html">
				<img src="http://seekingmichigan.org/images/teach-sub-btn-primary.jpg" alt="Using Primary Resources" />
				</a>
			</li>
			<li>
				<a href="http://seekingmichigan.org/coming-soon">
				<img src="http://seekingmichigan.org/images/teach-sub-btn-prof.jpg" alt="Professional Development" />
				</a>
			</li>
		</ul>
	</div>
	<div id="sidebar-btm">
	</div>
					
			       </div>
