<?php
// Background textures
$bgm_path = OF_DIRECTORY.'/images/bg/mini';
$background_textures = array('' => $bgm_path.'/blank.png', 'bg1' => $bgm_path.'/bg1.png', 'bg2' => $bgm_path.'/bg2.png', 'bg3' => $bgm_path.'/bg3.png', 'bg4' => $bgm_path.'/bg4.png', 'bg5' => $bgm_path.'/bg5.png',
							 'bg6' => $bgm_path.'/bg6.png', 'bg7' => $bgm_path.'/bg7.png', 'bg8' => $bgm_path.'/bg8.png', 'bg9' => $bgm_path.'/bg9.png', 'bg10' => $bgm_path.'/bg10.png',
							 'bg11' => $bgm_path.'/bg11.png', 'bg12' => $bgm_path.'/bg12.png', 'bg13' => $bgm_path.'/bg13.png', 'bg14' => $bgm_path.'/bg14.png', 'bg15' => $bgm_path.'/bg15.png',
							 'bg16' => $bgm_path.'/bg16.png', 'bg17' => $bgm_path.'/bg17.png', 'bg18' => $bgm_path.'/bg18.png', 'bg19' => $bgm_path.'/bg19.png', 'bg20' => $bgm_path.'/bg20.png',
							 'bg21' => $bgm_path.'/bg21.png', 'bg22' => $bgm_path.'/bg22.png', 'bg23' => $bgm_path.'/bg23.png', 'bg24' => $bgm_path.'/bg24.png', 'bg25' => $bgm_path.'/bg25.png',
							 'bg26' => $bgm_path.'/bg26.png', 'bg27' => $bgm_path.'/bg27.png', 'bg28' => $bgm_path.'/bg28.png', 'bg29' => $bgm_path.'/bg29.png', 'bg30' => $bgm_path.'/bg30.png', 
							 'bg31' => $bgm_path.'/bg31.png', 'bg32' => $bgm_path.'/bg32.png', 'bg33' => $bgm_path.'/bg33.png', 'bg34' => $bgm_path.'/bg34.png', 'bg35' => $bgm_path.'/bg35.png',
							 'bg36' => $bgm_path.'/bg36.png', 'bg37' => $bgm_path.'/bg37.png', 'bg38' => $bgm_path.'/bg38.png', 'bg39' => $bgm_path.'/bg39.png', 'bg40' => $bgm_path.'/bg40.png', 
							 'bg41' => $bgm_path.'/bg41.png', 'bg42' => $bgm_path.'/bg42.png', 'bg43' => $bgm_path.'/bg43.png', 'bg44' => $bgm_path.'/bg44.png', 'bg45' => $bgm_path.'/bg45.png', 
							 'bg46' => $bgm_path.'/bg46.png', 'bg47' => $bgm_path.'/bg47.jpg', 'bg48' => $bgm_path.'/bg48.jpg', 'bg49' => $bgm_path.'/bg49.jpg', 'bg50' => $bgm_path.'/bg50.jpg', 
							 'bg52' => $bgm_path.'/bg52.jpg', 'bg53' => $bgm_path.'/bg53.jpg', 'bg54' => $bgm_path.'/bg54.jpg', 'bg55' => $bgm_path.'/bg55.jpg',
							 'bg56' => $bgm_path.'/bg56.jpg', 'bg57' => $bgm_path.'/bg57.jpg', 'bg58' => $bgm_path.'/bg58.jpg', 'bg59' => $bgm_path.'/bg59.jpg', 'bg60' => $bgm_path.'/bg60.jpg',
							 'bg61' => $bgm_path.'/bg61.png', 'bg62' => $bgm_path.'/bg62.png', 'bg63' => $bgm_path.'/bg63.png', 'bg64' => $bgm_path.'/bg64.png', 'bg65' => $bgm_path.'/bg65.jpg',
							 'bg66' => $bgm_path.'/bg66.jpg', 'bg67' => $bgm_path.'/bg67.jpg', 'bg68' => $bgm_path.'/bg68.jpg', 'bg69' => $bgm_path.'/bg69.jpg', 'bg70' => $bgm_path.'/bg70.jpg',
							 'bg71' => $bgm_path.'/bg71.jpg', 'bg72' => $bgm_path.'/bg72.jpg', 'bg73' => $bgm_path.'/bg73.jpg', 'bg74' => $bgm_path.'/bg74.png', 'bg75' => $bgm_path.'/bg75.png',
							 'bg76' => $bgm_path.'/bg76.png', 'bg77' => $bgm_path.'/bg77.png', 'bg78' => $bgm_path.'/bg78.png', 'bg79' => $bgm_path.'/bg79.png', 'bg80' => $bgm_path.'/bg80.png',
							 'bg81' => $bgm_path.'/bg81.png', 'bg82' => $bgm_path.'/bg82.png', 'bg83' => $bgm_path.'/bg83.png', 'bg84' => $bgm_path.'/bg84.png', 'bg85' => $bgm_path.'/bg85.png',
							 'bg86' => $bgm_path.'/bg86.png', 'bg87' => $bgm_path.'/bg87.png', 'bg88' => $bgm_path.'/bg88.png', 'bg89' => $bgm_path.'/bg89.png', 'bg90' => $bgm_path.'/bg90.png',
							 'bg91' => $bgm_path.'/bg91.png', 'bg92' => $bgm_path.'/bg92.png', 'bg94' => $bgm_path.'/bg94.png', 'bg95' => $bgm_path.'/bg95.png',
							 'bg96' => $bgm_path.'/bg96.png', 'bg97' => $bgm_path.'/bg97.png', 'bg98' => $bgm_path.'/bg98.png', 'bg99' => $bgm_path.'/bg99.png', 'bg100' => $bgm_path.'/bg100.png',
							 'bg101' => $bgm_path.'/bg101.png', 'bg102' => $bgm_path.'/bg102.png', 'bg103' => $bgm_path.'/bg103.png', 'bg104' => $bgm_path.'/bg104.png', 'bg105' => $bgm_path.'/bg105.png',
							 'bg107' => $bgm_path.'/bg107.png', 'bg108' => $bgm_path.'/bg108.png', 'bg109' => $bgm_path.'/bg109.png', 'bg110' => $bgm_path.'/bg110.png',
							 'bg111' => $bgm_path.'/bg111.png', 'bg112' => $bgm_path.'/bg112.png', 'bg113' => $bgm_path.'/bg113.png');

$header_pictures = array('' => $bgm_path.'/blank.png', 'abstraction1' => $bgm_path.'/abstraction1.png', 'abstraction2' => $bgm_path.'/abstraction2.png', 'abstraction3' => $bgm_path.'/abstraction3.png',
							  'abstraction4' => $bgm_path.'/abstraction4.png', 'abstraction5' => $bgm_path.'/abstraction5.png', 'abstraction6' => $bgm_path.'/abstraction6.png');

$e404_default_logos = array('style_01' => 'logo',
							'style_02' => 'logo',
							'style_03' => 'logo',
							'style_04' => 'logo',
							'style_05' => 'logo',
							'style_06' => 'logo',
							'style_07' => 'logo',
							'style_08' => 'logo',
							'style_09' => 'logo',
							'style_10' => 'logo',
							'style_11' => 'logo',
							'style_12' => 'logo',
							'style_13' => 'logo',
							'style_14' => 'logo',
							'style_15' => 'logo',
							'style_16' => 'logo'
							);

$e404_default_icons = array('style_01' => 'black',
							'style_02' => 'white',
							'style_03' => 'black',
							'style_04' => 'black',
							'style_05' => 'white',
							'style_06' => 'black',
							'style_07' => 'white',
							'style_08' => 'white',
							'style_09' => 'white',
							'style_10' => 'black',
							'style_11' => 'black',
							'style_12' => 'white',
							'style_13' => 'black',
							'style_14' => 'black',
							'style_15' => 'black',
							'style_16' => 'black'
							);

$e404_default_transparency = array('style_01' => 'false',
                                   'style_02' => 'true',
                                   'style_03' => 'false',
                                   'style_04' => 'false',
                                   'style_05' => 'true',
                                   'style_06' => 'false',
                                   'style_07' => 'true',
                                   'style_08' => 'false',
                                   'style_09' => 'false',
                                   'style_10' => 'true',
                                   'style_11' => 'true',
                                   'style_12' => 'true',
                                   'style_13' => 'true',
                                   'style_14' => 'false',
                                   'style_15' => 'true',
                                   'style_16' => 'true'
                                   );

$e404_default_social_icons = array('style_01' => 'silver',
                                   'style_02' => 'color',
                                   'style_03' => 'silver',
                                   'style_04' => 'silver',
                                   'style_05' => 'silver',
                                   'style_06' => 'color',
                                   'style_07' => 'color',
                                   'style_08' => 'silver',
                                   'style_09' => 'silver',
                                   'style_10' => 'silver',
                                   'style_11' => 'silver',
                                   'style_12' => 'silver',
                                   'style_13' => 'silver',
                                   'style_14' => 'color',
                                   'style_15' => 'silver',
                                   'style_16' => 'silver'
                                   );
?>
